2018-12-12 13:36:37,953 INFO:             errors [in app.py:50]
2018-12-12 13:36:51,991 ERROR:             Exception on / [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 14, in main
    return render_template('index.html')
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2018-12-12 13:36:52,237 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 13:38:14,266 INFO:             errors [in app.py:50]
2018-12-12 13:38:22,719 ERROR:             Exception on / [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 14, in main
    return render_template('index.html')
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2018-12-12 13:38:22,962 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 13:39:49,398 ERROR:             Exception on / [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 14, in main
    return render_template('index.html')
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2018-12-12 13:39:49,650 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 13:55:02,983 INFO:             errors [in app.py:50]
2018-12-12 13:55:07,556 ERROR:             Exception on / [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 14, in main
    return render_template('index.html')
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\templates\index.html", line 1, in top-level template code
    {% extends "_base.html" %}
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _base.html
2018-12-12 13:55:07,771 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:03:34,862 INFO:             errors [in app.py:50]
2018-12-12 14:03:39,134 ERROR:             Exception on / [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 14, in main
    return render_template('templates/index.html')
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: templates/index.html
2018-12-12 14:03:39,379 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:03:54,203 ERROR:             Exception on / [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 14, in main
    return render_template('index.html')
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: templates/index.html
2018-12-12 14:03:54,452 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:10:00,617 INFO:             errors [in app.py:50]
2018-12-12 14:10:12,623 ERROR:             Exception on / [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 14, in main
    return render_template('index.html')
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\templates\index.html", line 1, in top-level template code
    {% extends "_base.html" %}
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _base.html
2018-12-12 14:10:12,832 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:13:29,913 ERROR:             Exception on /ocr [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:13:30,165 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:13:34,568 ERROR:             Exception on /ocr [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:13:34,918 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:13:40,518 ERROR:             Exception on /ocr [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:13:40,770 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:14:05,860 ERROR:             Exception on /ocr [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:14:06,111 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:16:40,542 ERROR:             Exception on / [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 14, in main
    return render_template('index.html')
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dojha\Downloads\pricing_api\venv\templates\index.html", line 1, in top-level template code
    <html>
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _base.html
2018-12-12 14:16:40,791 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:16:49,818 INFO:             errors [in app.py:50]
2018-12-12 14:16:53,920 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:17:28,237 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:18:37,681 ERROR:             Exception on /v{}/ocr [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:18:37,928 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:18:53,434 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:29:17,179 INFO:             errors [in app.py:50]
2018-12-12 14:29:24,606 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:29:31,354 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:34:18,466 INFO:             errors [in app.py:50]
2018-12-12 14:34:24,392 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:42:57,585 INFO:             errors [in app.py:50]
2018-12-12 14:43:06,596 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:46:40,880 INFO:             errors [in app.py:50]
2018-12-12 14:46:45,844 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:46:50,424 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:47:40,223 INFO:             errors [in app.py:50]
2018-12-12 14:47:42,941 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:47:55,418 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:51:26,633 INFO:             errors [in app.py:50]
2018-12-12 14:51:33,709 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:51:57,686 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:51:58,549 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:52:14,680 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:53:05,455 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:53:20,118 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:54:45,406 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:55:02,188 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:55:30,713 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:55:32,665 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:55:43,821 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:55:44,481 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:56:05,151 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:56:15,101 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:57:39,845 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:57:40,510 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:57:42,385 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:59:18,553 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:59:27,021 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:59:44,147 INFO:             errors [in app.py:50]
2018-12-12 14:59:47,646 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 14:59:59,436 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:00:20,187 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:00:23,618 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:00:36,796 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:00:40,023 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:00:42,289 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:00:49,274 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:01:49,547 INFO:             errors [in app.py:50]
2018-12-12 15:01:56,393 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:02:06,065 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:02:28,457 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:02:31,609 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:02:37,368 ERROR:             Exception on /v1 [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:02:37,751 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:02:41,546 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:02:55,589 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:03:08,284 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:03:52,430 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:03:54,985 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:13:28,016 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:13:41,639 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:10,673 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:11,863 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:12,393 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:13,243 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:15,970 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:20,612 INFO:             errors [in app.py:50]
2018-12-12 15:14:23,865 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:31,117 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:49,207 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:55,442 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:14:58,130 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:15:03,144 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:15:04,699 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:16:09,618 ERROR:             Exception on /v1/ocr/https://www.techperiod.com/wp-content/uploads/2015/12/reverse-google-image-search-featured.png [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:16:09,906 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:16:22,874 ERROR:             Exception on /v{1}/ocr/https://www.techperiod.com/wp-content/uploads/2015/12/reverse-google-image-search-featured.png [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:16:23,144 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:16:34,413 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:19:12,652 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:36:30,901 INFO:             errors [in app.py:53]
2018-12-12 15:36:41,730 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:36:52,024 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:36:57,624 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:36:59,344 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:36:59,789 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:37:12,333 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:43:08,768 INFO:             errors [in app.py:51]
2018-12-12 15:43:13,361 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:45:55,953 ERROR:             Exception on /v1/ocr/https://www.techperiod.com/wp-content/uploads/2015/12/reverse-google-image-search-featured.png [POST] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:46:11,795 ERROR:             Exception on /v1/ocr/ [POST] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 15:46:23,175 INFO:             errors [in app.py:51]
2018-12-12 15:46:47,952 ERROR:             Exception on /v1/ocr/https://cdn.fstoppers.com/styles/large-16-9/s3/lead/2018/02/google-getty-images-change-image-search-to-improve-copyright-protections.jpg [POST] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 16:01:57,274 INFO:             errors [in app.py:51]
2018-12-12 16:01:59,875 ERROR:             Exception on /v1/ocr/https://cdn.fstoppers.com/styles/large-16-9/s3/lead/2018/02/google-getty-images-change-image-search-to-improve-copyright-protections.jpg [POST] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 16:04:10,982 ERROR:             Exception on /v1/ocr/https://www.techperiod.com/wp-content/uploads/2015/12/reverse-google-image-search-featured.png [POST] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 16:16:23,988 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 16:17:25,867 ERROR:             Exception on /v1/ocr/https://i.ytimg.com/vi/gTrLniP5tSQ/maxresdefault.jpg [POST] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 16:18:22,278 ERROR:             Exception on /v1/ocr/https://i.ytimg.com/vi/gTrLniP5tSQ/maxresdefault.jpg [POST] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 16:18:28,317 ERROR:             Exception on /v1/ocr/https://i.ytimg.com/vi/gTrLniP5tSQ/maxresdefault.jpg [POST] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 16:19:27,395 ERROR:             Exception on /v1/ocr/https://i.ytimg.com/vi/gTrLniP5tSQ/maxresdefault.jpg [POST] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-12 16:22:06,510 INFO:             errors [in app.py:51]
2018-12-12 16:22:48,885 INFO:             errors [in app.py:51]
2018-12-12 16:46:42,299 INFO:             errors [in app.py:51]
2018-12-12 16:48:33,261 INFO:             errors [in app.py:51]
2018-12-12 16:53:55,750 INFO:             errors [in app.py:51]
2018-12-12 16:55:08,678 INFO:             errors [in app.py:51]
2018-12-12 16:59:12,223 INFO:             errors [in app.py:51]
2018-12-12 17:00:04,082 INFO:             errors [in app.py:49]
2018-12-12 17:00:48,328 INFO:             errors [in app.py:46]
2018-12-12 17:01:39,604 INFO:             errors [in app.py:51]
2018-12-12 17:08:08,320 INFO:             errors [in app.py:51]
2018-12-13 09:04:55,661 INFO:             errors [in app.py:51]
2018-12-13 09:05:14,929 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-13 09:07:40,661 ERROR:             Exception on /favicon.ico [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-12-13 13:46:20,214 INFO:             errors [in C:\Users\dojha\Downloads\pricing_api\venv\app.py:51]
2018-12-13 15:02:14,142 INFO:             errors [in app.py:51]
2018-12-13 15:05:22,496 ERROR:             Exception on /v1/ocr/https://pbs.twimg.com/media/CIsnPb3UsAAyFMz.png [GET] [in C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\dojha\Downloads\pricing_api\venv\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
